require: rubocop-rspec

LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Documentation:
  Enabled: False

FactoryBot/AttributeDefinedStatically:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

WordArray:
  Enabled: False

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
